package claude

import "testing"

func TestClaudeUserTitle(t *testing.T) {
	tests := []struct {
		in   string
		want string
		ok   bool
	}{
		{
			in:   "<command-message>pro-pentest-operator</command-message>\n<command-name>/pro-pentest-operator</command-name>",
			want: "/pro-pentest-operator",
			ok:   true,
		},
		{
			in:   "<command-name>/model</command-name>",
			want: "",
			ok:   false,
		},
		{
			in:   "<command-name>/pro-pentest-operator</command-name>",
			want: "/pro-pentest-operator",
			ok:   true,
		},
		{
			in:   "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands</local-command-caveat>",
			want: "",
			ok:   false,
		},
		{
			in:   "hello",
			want: "hello",
			ok:   true,
		},
		{
			in:   "is claude mem enabled on here?",
			want: "is claude mem enabled on here?",
			ok:   true,
		},
	}
	for _, tc := range tests {
		got, ok := claudeUserTitle(tc.in)
		if ok != tc.ok || got != tc.want {
			t.Fatalf("claudeUserTitle(%q) = (%q, %v), want (%q, %v)", tc.in, got, ok, tc.want, tc.ok)
		}
	}
}
